[package]
name = "playlist_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
iced = "0.13.1"
iced_aw = "0.12.2"
rfd = "0.15.4"
serde = "1.0.219"
serde_json = "1.0.141"
tempfile = "3.20.0"
