max_width = 80
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Max"
edition = "2021"
newline_style = "Unix"

reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

wrap_comments = true
format_code_in_doc_comments = true
match_block_trailing_comma = true
