# https://github.com/moonrepo/setup-rust
name: Rust CI
on:
  push:
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: moonrepo/setup-rust@v1.2.2
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all --check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: moonrepo/setup-rust@v1.2.2
        with:
          bins: cargo-make, cargo-nextest
      - name: Run tests
        run: cargo make test
